/*

@license
dhtmlxScheduler v.5.3.9 Standard

To use dhtmlxScheduler in non-GPL projects (and get Pro version of the product), please obtain Commercial/Enterprise or Ultimate license on our site https://dhtmlx.com/docs/products/dhtmlxScheduler/#licensing or contact us at sales@dhtmlx.com

(c) XB Software Ltd.

*/
Scheduler.plugin(function(t){t._get_serializable_data=function(){var t={};for(var e in this._events){var a=this._events[e];-1==a.id.toString().indexOf("#")&&(t[a.id]=a)}return t},t.data_attributes=function(){var e=[],a=t._helpers.formatDate,r=this._get_serializable_data();for(var n in r){var i=r[n];for(var s in i)"_"!=s.slice(0,1)&&e.push([s,"start_date"==s||"end_date"==s?a:null]);break}return e},t.toXML=function(t){var e=[],a=this.data_attributes(),r=this._get_serializable_data();for(var n in r){var i=r[n];e.push("<event>");for(var s=0;s<a.length;s++)e.push("<"+a[s][0]+"><![CDATA["+(a[s][1]?a[s][1](i[a[s][0]]):i[a[s][0]])+"]]></"+a[s][0]+">");e.push("</event>")}return(t||"")+"<data>"+e.join("\n")+"</data>"},t._serialize_json_value=function(t){return null===t||"boolean"==typeof t?t=""+t:(t||0===t||(t=""),t='"'+t.toString().replace(/\n/g,"").replace(/\\/g,"\\\\").replace(/\"/g,'\\"')+'"'),t},t.toJSON=function(){var t=[],e="",a=this.data_attributes(),r=this._get_serializable_data();for(var n in r){for(var i=r[n],s=[],_=0;_<a.length;_++)e=a[_][1]?a[_][1](i[a[_][0]]):i[a[_][0]],s.push(' "'+a[_][0]+'": '+this._serialize_json_value(e));t.push("{"+s.join(",")+"}")}return"["+t.join(",\n")+"]"},t.toICal=function(e){var a=t.date.date_to_str("%Y%m%dT%H%i%s"),r=t.date.date_to_str("%Y%m%d"),n=[],i=this._get_serializable_data();for(var s in i){var _=i[s];n.push("BEGIN:VEVENT"),_._timed&&(_.start_date.getHours()||_.start_date.getMinutes())?n.push("DTSTART:"+a(_.start_date)):n.push("DTSTART:"+r(_.start_date)),_._timed&&(_.end_date.getHours()||_.end_date.getMinutes())?n.push("DTEND:"+a(_.end_date)):n.push("DTEND:"+r(_.end_date)),n.push("SUMMARY:"+_.text),n.push("END:VEVENT")}return"BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//dhtmlXScheduler//NONSGML v2.2//EN\nDESCRIPTION:"+(e||"")+"\n"+n.join("\n")+"\nEND:VCALENDAR"}});
//# sourceMappingURL=sources/ext/dhtmlxscheduler_serialize.js.map