/*

@license
dhtmlxScheduler v.5.3.9 Standard

To use dhtmlxScheduler in non-GPL projects (and get Pro version of the product), please obtain Commercial/Enterprise or Ultimate license on our site https://dhtmlx.com/docs/products/dhtmlxScheduler/#licensing or contact us at sales@dhtmlx.com

(c) XB Software Ltd.

*/
Scheduler.plugin(function(e){e.date.date_to_str=function(t,a){return function(r){return t.replace(/%[a-zA-Z]/g,function(t){switch(t){case"%d":return a?e.date.to_fixed(r.getUTCDate()):e.date.to_fixed(r.getDate());case"%m":return a?e.date.to_fixed(r.getUTCMonth()+1):e.date.to_fixed(r.getMonth()+1);case"%j":return a?r.getUTCDate():r.getDate();case"%n":return a?r.getUTCMonth()+1:r.getMonth()+1;case"%y":return a?e.date.to_fixed(r.getUTCFullYear()%100):e.date.to_fixed(r.getFullYear()%100);case"%Y":return a?r.getUTCFullYear():r.getFullYear();case"%D":return a?e.locale.date.day_short[r.getUTCDay()]:e.locale.date.day_short[r.getDay()];case"%l":return a?e.locale.date.day_full[r.getUTCDay()]:e.locale.date.day_full[r.getDay()];case"%M":return a?e.locale.date.month_short[r.getUTCMonth()]:e.locale.date.month_short[r.getMonth()];case"%F":return a?e.locale.date.month_full[r.getUTCMonth()]:e.locale.date.month_full[r.getMonth()];case"%h":return a?e.date.to_fixed((r.getUTCHours()+11)%12+1):e.date.to_fixed((r.getHours()+11)%12+1);case"%g":return a?(r.getUTCHours()+11)%12+1:(r.getHours()+11)%12+1;case"%G":return a?r.getUTCHours():r.getHours();case"%H":return a?e.date.to_fixed(r.getUTCHours()):e.date.to_fixed(r.getHours());case"%i":return a?e.date.to_fixed(r.getUTCMinutes()):e.date.to_fixed(r.getMinutes());case"%a":return a?r.getUTCHours()>11?"pm":"am":r.getHours()>11?"pm":"am";case"%A":return a?r.getUTCHours()>11?"PM":"AM":r.getHours()>11?"PM":"AM";case"%s":return a?e.date.to_fixed(r.getUTCSeconds()):e.date.to_fixed(r.getSeconds());case"%W":return a?e.date.to_fixed(e.date.getUTCISOWeek(r)):e.date.to_fixed(e.date.getISOWeek(r));default:return t}})}},e.date.str_to_date=function(t,a){return function(r){for(var o=[0,0,1,0,0,0],s=r.match(/[a-zA-Z]+|[0-9]+/g),n=t.match(/%[a-zA-Z]/g),c=0;c<n.length;c++)switch(n[c]){case"%j":case"%d":o[2]=s[c]||1;break;case"%n":case"%m":o[1]=(s[c]||1)-1;break;case"%y":o[0]=1*s[c]+(s[c]>50?1900:2e3);break;case"%g":case"%G":case"%h":case"%H":o[3]=s[c]||0;break;case"%i":o[4]=s[c]||0;break;case"%Y":o[0]=s[c]||0;break;case"%a":case"%A":o[3]=o[3]%12+("am"==(s[c]||"").toLowerCase()?0:12);break;case"%s":o[5]=s[c]||0;break;case"%M":o[1]=e.locale.date.month_short_hash[s[c]]||0;break;case"%F":o[1]=e.locale.date.month_full_hash[s[c]]||0}return a?new Date(Date.UTC(o[0],o[1],o[2],o[3],o[4],o[5])):new Date(o[0],o[1],o[2],o[3],o[4],o[5])}}});
//# sourceMappingURL=sources/ext/dhtmlxscheduler_csp.js.map