/*

@license
dhtmlxScheduler v.5.3.9 Standard

To use dhtmlxScheduler in non-GPL projects (and get Pro version of the product), please obtain Commercial/Enterprise or Ultimate license on our site https://dhtmlx.com/docs/products/dhtmlxScheduler/#licensing or contact us at sales@dhtmlx.com

(c) XB Software Ltd.

*/
Scheduler.plugin(function(t){!function(){t.config.all_timed="short",t.config.all_timed_month=!1;var e=function(e){return!((e.end_date-e.start_date)/36e5>=24)||"resize"==t._drag_mode&&t._drag_id==e.id};t._safe_copy=function(e){var _=null,a=t._copy_event(e);return e.event_pid&&(_=t.getEvent(e.event_pid)),_&&_.isPrototypeOf(e)&&(delete a.event_length,delete a.event_pid,delete a.rec_pattern,delete a.rec_type),a};var _=t._pre_render_events_line,a=t._pre_render_events_table,n=function(t,e){return this._table_view?a.call(this,t,e):_.call(this,t,e)};t._pre_render_events_line=t._pre_render_events_table=function(_,a){if(!this.config.all_timed||this._table_view&&"month"!=this._mode||"month"==this._mode&&!this.config.all_timed_month)return n.call(this,_,a);for(var i=0;i<_.length;i++){var r=_[i];if(!r._timed)if("short"!=this.config.all_timed||e(r)){var d=this._safe_copy(r);r._virtual?d._first_chunk=!1:d._first_chunk=!0,d._drag_resize=!1,d._virtual=!0,d.start_date=new Date(d.start_date),c(r)?(d.end_date=h(d.start_date),24!=this.config.last_hour&&(d.end_date=u(d.start_date,this.config.last_hour))):d.end_date=new Date(r.end_date);var s=!1;d.start_date<this._max_date&&d.end_date>this._min_date&&d.start_date<d.end_date&&(_[i]=d,s=!0);var l=this._safe_copy(r);if(l._virtual=!0,l.end_date=new Date(l.end_date),l.start_date<this._min_date?l.start_date=u(this._min_date,this.config.first_hour):l.start_date=u(h(r.start_date),this.config.first_hour),l.start_date<this._max_date&&l.start_date<l.end_date){if(!s){_[i--]=l;continue}_.splice(i+1,0,l),l._last_chunk=!1}else d._last_chunk=!0,d._drag_resize=!0}else"month"!=this._mode&&_.splice(i--,1)}var o="move"!=this._drag_mode&&a;return n.call(this,_,o);function c(t){var e=h(t.start_date);return+t.end_date>+e}function h(e){var _=t.date.add(e,1,"day");return _=t.date.date_part(_)}function u(e,_){var a=t.date.date_part(new Date(e));return a.setHours(_),a}};var i=t.get_visible_events;t.get_visible_events=function(t){return this.config.all_timed&&this.config.multi_day?i.call(this,!1):i.call(this,t)},t.attachEvent("onBeforeViewChange",function(e,_,a,n){return t._allow_dnd="day"==a||"week"==a,!0}),t._is_main_area_event=function(t){return!!(t._timed||!0===this.config.all_timed||"short"==this.config.all_timed&&e(t))};var r=t.updateEvent;t.updateEvent=function(e){var _,a,n=t.getEvent(e);n&&(_=t.config.all_timed&&!(t.isOneDayEvent(t._events[e])||t.getState().drag_id))&&(a=t.config.update_render,t.config.update_render=!0),r.apply(t,arguments),n&&_&&(t.config.update_render=a)}}()});
//# sourceMappingURL=sources/ext/dhtmlxscheduler_all_timed.js.map