"""
Markdown <-> HTML via a middle JSON tree, using tree-sitter for parsing.
Generated by Claude Opus 4.8 High

Middle node shape (plain dicts):
    {"type": "...", "children": [...], "text": "...", ...extra fields}

Block types:    document, metadata(format), heading(level), paragraph,
                blockquote, list(ordered,start), list_item(is_checked), code_block(lang),
                thematic_break, table, table_row(header), table_cell
Inline types:   text, italic, strong, emphasis, strikethrough, code_span,
                link(url,text), image(url,text), embed(url, text), wikilink(url, text), softbreak(I didn't detect the real usage of this rule), hardbreak

Here to simplify the structure: 
    link: `[text](url)`, if text isn't set, text = url
    image: `![text](url)`, if text isn't set, text = url
    wikilink: `[[url|text]]`, if text isn't set, `[[url]]`
    embed: `![[url|text]]`, if text isn't set, `![[url]]`
    list: only `-`
    table: only `|---|...|---|`
    
Public API:
    parse_markdown(md)  -> middle      (tree-sitter; GFM extensions)
        - Current tradeoffs:
            1. some elements that allow multi-lines(without the need of double newlines) including latex_block, blockquote, I would treat the whole block as a paragraph with "\n" inside its text node. Somtimes those blocks would be fused into other paragraph.
                - For normally I won't edit those kinds of blocks 
                - however, the "\n" won't be visible from html or from the console of browser, the important newlines only existed in the html source code. We keep our scenes restricted so right now we use the html source code to save those data.
                - In the future, I might set a flag to show if a paragraph can be parsed into those block or if any of these blocks need to split inner paragraph containing "\n" into multiple paragraphs, we then also need to parse those paragraphs back and remove the additional lines.
            2. comments, references are treated as visible paragraphs instead of invisible special elements to avoid missing them and to get better conversion.
            3. softbreak: I didn't detect the usage of softbreak inside treesitter-markdown, so I directly throw a ValueError
            4. block_continuation: block that needd block_continuation, like backquote, might wrongly distributed the startbyte and endbyte of a node. we use _txt_by_lines to backsearch few bytes until newline since multi line blocks always startswith newline and endswith newline.
            5. 
    parse_html(html)    -> middle      (tree-sitter)
        - Current tradeoffs:
            A: from html generated via formats.py from markdown
            B: from html generated by uploading markdown to slack canvas then downloading
    dump_markdown(node) -> md          (pure)
        - Current tradeoffs:
    dump_html(node)     -> html        (pure)
        - Current tradeoffs:
    markdown_to_html(md)
    
    html_to_markdown(html)

NOTE: tree-sitter-markdown ships the GFM extensions (task lists, strikethrough, pipe tables) and minus/plus metadata by default.
"""

import re
import json
import html
import sys
import tree_sitter
import tree_sitter_html
import tree_sitter_markdown

sys.stdout.reconfigure(encoding="utf-8")

# ===========================================================================
# tree-sitter loading (version-tolerant)
# ===========================================================================


def _make_parser(lang):
    try:
        return tree_sitter.Parser(lang)                 # tree_sitter >= 0.22
    except TypeError:
        p = tree_sitter.Parser()
        if hasattr(p, "set_language"):
            p.set_language(lang)            # tree_sitter < 0.22
        else:
            p.language = lang
        return p


def _languages():
    html_lang = tree_sitter.Language(tree_sitter_html.language())
    block_lang = tree_sitter.Language(tree_sitter_markdown.language())
    inline_lang = tree_sitter.Language(tree_sitter_markdown.inline_language())
    return html_lang, block_lang, inline_lang


def _txt(node, src):
    return _txt2(node.start_byte, node.end_byte, src)

def _txt2(start_byte, end_byte, src):
    return src[start_byte:end_byte].decode("utf-8").replace("\u00a0", " ").replace("\u2014", "-").replace("\u2026", "-")

def _esc(s):
    return html.escape(s, quote=False)

def text_only4node(node):
    if "children" not in node:
        return _md_inline([node])
    return _md_inline(node["children"])

# ===========================================================================
# MARKDOWN -> middle
# ===========================================================================
# Node-name constants — VERIFY against your installed grammar (see diagnose()).
MD = dict(
    heading="atx_heading", setext="setext_heading",
    paragraph="paragraph", blockquote="block_quote",
    list="list", list_item="list_item",
    fenced="fenced_code_block", indented="indented_code_block",
    table="pipe_table", thematic="thematic_break",
    inline="inline", yaml_meta="minus_metadata", toml_meta="plus_metadata",
)


def dump_treesitter_tree(node, src: bytes, depth=0):
    text = src[node.start_byte:node.end_byte].decode("utf-8", "replace")
    snippet = text if len(text) <= 40 else text[:37] + "..."
    print("  " * depth + f"{node.type}  "
          f"[{node.start_point}-{node.end_point}]  "
          f"named={node.is_named}  text={snippet!r}")
    for child in node.children:
        dump_treesitter_tree(child, src, depth + 1)

def merge_text(nodes):
    merged = []
    for n in nodes:
        if (n["type"] == "text" and merged and merged[-1]["type"] == "text"):
            merged[-1]["text"] += n["text"]
        else:
            merged.append(n)
    return merged

def recover_abnormal_children(f):
    def wrap(*args, **kwargs):
        midnode = f(*args, **kwargs)
        if midnode is not None:
            for c in list(midnode.get("children", [])):
                if "abnormal_children" in c:
                    midnode["children"] += c["abnormal_children"]
                    c.pop("abnormal_children")
        return midnode
    return wrap

def parse_markdown(text):
    _, block_lang, inline_lang = _languages()
    block_parser = _make_parser(block_lang)
    inline_parser = _make_parser(inline_lang)
    src = text.encode("utf-8")
    tree = block_parser.parse(src)
    dump_treesitter_tree(tree.root_node, src)  # debug
    
    def _txt_by_lines(node, subsrc):
        # only workable in markdown
        start_byte = node.start_byte
        end_byte = node.end_byte
        while start_byte > 0 and subsrc[start_byte] != 0x0a:
            start_byte -= 1
        while end_byte > start_byte and subsrc[end_byte - 1] == 0x20:
            end_byte -= 1
        while end_byte < len(subsrc) and subsrc[end_byte - 1] != 0x0a:
            end_byte += 1
        return _txt2(start_byte, end_byte, subsrc)

    def parse_inline(text):
        b = text.encode("utf-8")
        itree = inline_parser.parse(b)
        dump_treesitter_tree(itree.root_node, b)
        return _inline_children(itree.root_node, b)

    def parse_inline_blocks(text):
        b = text.encode("utf-8")
        itree = block_parser.parse(b)
        dump_treesitter_tree(itree.root_node, b)
        children = [block(c, subsrc=b) for c in itree.root_node.children if _is_block(c)]
        return children

    def _inline_children(node, b):
        out = []
        pos = node.start_byte
        children = list(node.children)
        i = 0
        while i < len(children):
            ch = children[i]
            # Detect [[wikilink]]: text "[" + shortcut_link + text "]"
            if (ch.type == "text" and _txt(ch, b) == "["
                    and i + 2 < len(children)
                    and children[i + 1].type == "shortcut_link"
                    and children[i + 2].type == "text" and _txt(children[i + 2], b) == "]"):
                if ch.start_byte > pos:
                    text = b[pos:ch.start_byte].decode("utf-8")
                    out.append({"type": "text", "text": text})
                lt = _txt(next(c for c in children[i + 1].children if c.type == "link_text"), b)
                parts = lt.split("|", 1)
                out.append({"type": "wikilink", "url": parts[0], "text": parts[1] if len(parts) > 1 else ""})
                pos = children[i + 2].end_byte
                i += 3
                continue
            if ch.start_byte > pos:
                text = b[pos:ch.start_byte].decode("utf-8")
                out.append({"type": "text", "text": text})
            out.extend(_inline_node(ch, b))
            pos = ch.end_byte
            i += 1
        if pos < node.end_byte:
            text = b[pos:node.end_byte].decode("utf-8")
            out.append({"type": "text", "text": text})
        if not node.children and node.type == "inline":
            return [{"type": "text", "text": _txt(node, b)}]
        return merge_text(out)

    def _inline_node(n, b):
        t = n.type
        if t in ("emphasis_delimiter", "code_span_delimiter"):
            return []
        if t in ("italic", "emphasis", "strong_emphasis"):
            mapped = {"emphasis": "emphasis", "strong_emphasis": "strong",
                      "italic": "italic"}[t]
            return [{"type": mapped, "children": _inline_children(n, b)}]
        if t == "strikethrough":
            non_delim = [c for c in n.children
                         if c.type not in ("emphasis_delimiter",)]
            if len(non_delim) == 1 and non_delim[0].type == "strikethrough":
                return [{"type": "strikethrough",
                         "children": _inline_children(non_delim[0], b)}]
            return [{"type": "strikethrough", "children": _inline_children(n, b)}]
        if t == "code_span":
            text = _txt(n, b)
            assert text.startswith("`") and text.endswith("`")
            return [{"type": "code_span", "text": text[1:-1]}]
        if t in ("inline_link", "link"):
            text = url = ""
            for c in n.children:
                if c.type in ("link_text",):
                    text = _txt(c, b)
                elif c.type == "link_destination":
                    url = _txt(c, b)
                # elif c.type == "link_title":
                #     title = _txt(c, b).strip("\"'")
            return [{"type": "link", "url": url, "text": text}]
        if t == "image":
            url = ""
            has_link_dest = False
            for c in n.children:
                # We deliberately set text as alt
                if c.type == "image_description":
                    text = _txt(c, b)
                if c.type == "link_destination":
                    url = _txt(c, b)
                    has_link_dest = True
                # elif c.type == "link_title":
                #     title = _txt(c, b).strip("\"'")
            # Obsidian embed ![[...]] has no link_destination
            if not has_link_dest:
                for c in n.children:
                    if c.type == "image_description":
                        for cc in c.children:
                            if cc.type == "shortcut_link":
                                lt_node = next((x for x in cc.children if x.type == "link_text"), None)
                                if lt_node:
                                    lt = _txt(lt_node, b)
                                    parts = lt.split("|", 1)
                                    return [{"type": "embed", "url": parts[0], "text": parts[1] if len(parts) > 1 else ""}]
                return [{"type": "text", "text": _txt(n, b)}]
            return [{"type": "image", "url": url, "text": text}]
        if t in ("hard_line_break",):
            return [{"type": "hardbreak"}]
        if t in ("soft_line_break",):
            raise ValueError("thought soft_line_break is dead!")
            # return [{"type": "softbreak"}]
        # leaf text / anything unhandled -> raw text
        if n.child_count == 0:
            return [{"type": "text", "text": _txt(n, b)}]
        return _inline_children(n, b)


    @recover_abnormal_children
    def block(node, subsrc):
        t = node.type
        if t in (MD["heading"], MD["setext"]):
            level = 1
            for c in node.children:
                if c.type.startswith("atx_h") and c.type.endswith("_marker"):
                    level = c.type.count("h") and int(
                        c.type[5])  # atx_h3_marker
                if c.type == "setext_h1_underline":
                    level = 1
                if c.type == "setext_h2_underline":
                    level = 2
            inline = next(
                (c for c in node.children if c.type == MD["inline"]), None)
            kids = parse_inline(_txt(inline, subsrc)) if inline else []
            return {"type": "heading", "level": level, "children": kids}
        if t == MD["paragraph"]:
            inline = next(
                (c for c in node.children if c.type == MD["inline"]), None)
            kids = parse_inline(_txt(inline, subsrc)) if inline else parse_inline(_txt(node, subsrc))
            return {"type": "paragraph", "children": kids}
        if t == MD["blockquote"]:
            lines = []
            # treesitter bug
            abnormal_lines = [] # treesitter attached siblings into that block wrongly
            for line in _txt(node, subsrc).splitlines():
                if len(abnormal_lines) == 0 and line.startswith(">"):
                    lines.append(line[1:].lstrip())
                else:
                    abnormal_lines.append(line)
            children = parse_inline_blocks("\n".join(lines))
            res = {"type": "blockquote", "children": children}
            if len(abnormal_lines) > 0:
                res["abnormal_children"] = parse_inline_blocks("\n".join(abnormal_lines))
            return res
        if t == MD["list"]:
            items = [c for c in node.children if c.type == MD["list_item"]]
            ordered = False
            start = 1
            for it in items:
                for c in it.children:
                    if c.type.startswith("list_marker"):
                        mk = _txt(c, subsrc).strip()
                        if mk[:1].isdigit():
                            ordered = True
                            start = int(
                                "".join(ch for ch in mk if ch.isdigit()) or 1)
                        break
                break
            return {"type": "list", "ordered": ordered, "start": start,
                    "children": [list_item(it, subsrc=subsrc) for it in items]}
        if t == MD["fenced"]:
            lines = _txt_by_lines(node, subsrc).lstrip('\n').splitlines()
            assert lines[0].strip().startswith("```") and lines[-1].strip().startswith('```')
            level = lines[0].index('`') // 4
            for line in lines[1:-1]:
                assert line.startswith("    " * level)
            lang = lines[0].strip().lstrip("`").strip()
            code = "\n".join(line[4*level:] for line in lines[1:-1])
            return {"type": "code_block", "lang": lang, "level": level, "text": code.rstrip("\n")}
        if t == MD["indented"]:
            return {"type": "code_block", "lang": "",
                    "text": _txt(node, subsrc).rstrip("\n")}
        if t == MD["table"]:
            return parse_table(node, subsrc=subsrc)
        if t == MD["thematic"]:
            return {"type": "thematic_break"}
        if t == MD["yaml_meta"]:
            return {"type": "metadata", "format": "yaml",
                    "text": _txt(node, subsrc).strip().strip("-").strip()}
        if t == MD["toml_meta"]:
            return {"type": "metadata", "format": "toml",
                    "text": _txt(node, subsrc).strip().strip("+").strip()}
        if t in ("link_reference_definition",):
            return {"type": "paragraph", "children": [{"type": "text", "text": _txt(node, subsrc)}]}
        # containers like 'section' -> descend
        kids = [block(c, subsrc=subsrc) for c in node.children if _is_block(c)]
        kids = [k for k in kids if k]
        if len(kids) == 1:
            return kids[0]
        return {"type": "document", "children": kids} if kids else None

    def _is_block(c):
        return c.type in set(MD.values()) | {"section"} or c.type.endswith("_block") \
            or c.type in ("list_item", "link_reference_definition")

    def list_item(it, subsrc):
        is_checked = None
        for c in it.children:
            if c.type == "task_list_marker_checked":
                is_checked = "checked"
            elif c.type == "task_list_marker_unchecked":
                is_checked = "unchecked"
        kids = [block(c, subsrc) for c in it.children if _is_block(c)]
        kids = [k for k in kids if k]
        return {"type": "list_item", "is_checked": is_checked, "children": kids}

    def parse_table(node, subsrc):
        rows = []
        align = []
        for c in node.children:
            if c.type == "pipe_table_header":
                rows.append(table_row(c, header=True, subsrc=subsrc))
            elif c.type == "pipe_table_row":
                rows.append(table_row(c, header=False, subsrc=subsrc))
            elif c.type == "pipe_table_delimiter_row":
                for d in c.children:
                    if d.type == "pipe_table_delimiter_cell":
                        s = _txt(d, subsrc).strip()
                        left, right = s.startswith(":"), s.endswith(":")
                        align.append("center" if left and right else
                                     "right" if right else
                                     "left" if left else None)
        return {"type": "table", "align": align, "children": rows}

    def table_row(c, header, subsrc):
        cells = []
        for cell in c.children:
            if cell.type == "pipe_table_cell":
                inline = _txt(cell, subsrc)
                cells.append({"type": "table_cell",
                              "children": parse_inline(inline)})
        return {"type": "table_row", "header": header, "children": cells}

    root = tree.root_node
    children = [block(c, src) for c in root.children if _is_block(c)]
    children = [c for c in children if c is not None]
    result = {"type": "document", "children": children}
    return result


# ===========================================================================
# HTML -> middle
# ===========================================================================
_TAG_LEVEL = {f"h{i}": i for i in range(1, 7)}

"""
parse_html(text)
  -- tree = parser.parse(text)          # tree-sitter HTML parse
      -- for each root child `c` (type=="element"):
          -- block_node(c)              # tag-based dispatch 	 "p", "h1", "ul", etc.
              -
              -  -- tag == "h1..h6"  	 {"type": "heading", "children": inline_children(el)}
              -  -- tag == "p"       	 {"type": "paragraph", "children": inline_children(el)}
              -  -                      (special: if class="prettyprint line" 	 code_block via text_only)
              -  -- tag == "blockquote" 	 {"type": "blockquote", "children": blocks_in(el)}
              -  -                               -- blocks_in(el)
              -  -                                    -- for each child element 	 block_node(c) [RECURSION]
              -  -- tag in ("ul","ol") 	 {"type": "list", "children": li_node(c) for <li>}
              -  -                               -- li_node(el)
              -  -                                    -- blocks_in(el)  	 block_node sub-children
              -  -                                    -- if no blocks 	 inline_children(el) 	 wrap in paragraph
              -  -- tag == "pre"     	 code_block via text_only(el)
              -  -- tag == "hr"      	 thematic_break
              -  -- tag == "table"   	 html_table(el)
              -  -                        -- walk_rows 	 inline_children(td/th)
              -  -- else (div,body...) 	 blocks_in(el) 	 block_node(c) [RECURSION]
              -
              -  ------------------------------------------------------------------â
              -  -  inline_children(el)   â central inline workhorse               -
              -  -    for each child c in el.children:                             -
              -  -      type == "text"       	 {"type": "text", "text": ...}       -
              -  -      type == "entity"     	 {"type": "text", "text": ...}       -
              -  -      type == "element"    	 inline_node(c)  or  inline_children(c)-
              -  -      type == "start_tag" / "self_closing_tag"                   -
              -  -         if tag == "br"    	 {"type": "hardbreak"}               -
              -  -      type == "comment" / "doctype" 	 skip                       -
              -  -    then: _merge_text(out) (merge adjacent text nodes)           -
              -  -    then: check attrs_of(el) for href 	 link node               -
              -  ------------------------------------------------------------------
              -
              -  ------------------------------------------------------------------â
              -  -  inline_node(el)   â called from inline_children for <element>  -
              -  -    tag_of(el) dispatches:                                        -
              -  -      strong/b/em/i/del/s  	 semantic wrapper                    -
              -  -                               -- inline_children(el)            -
              -  -      code                	 code_span via _md_inline(inline_children(el)) -
              -  -      a                   	 link with children=inline_children(el)-
              -  -      img                 	 image (no inline_children)             -
              -  -      br                  	 hardbreak                              -
              -  -      else                	 inline_children(el)  [fallthrough]    -
              -  ------------------------------------------------------------------
              -
              -  ------------------------------------------------------------------
              -  -  text_only(el)   â used by pre/code/p (prettyprint)             -
              -  -    Walks children similarly but returns plain text string,       -
              -  -    not middle JSON nodes. Handles text, entity, element (recursive),-
              -  -    br 	 "  \n"                                                    -
              -  ------------------------------------------------------------------
"""


def parse_html(text):
    html_lang, _, _ = _languages()
    parser = _make_parser(html_lang)
    src = text.encode("utf-8")
    tree = parser.parse(src)

    def direct_tag_of(el):
        assert el.type in ("start_tag", "self_closing_tag")
        for cc in el.children:
            if cc.type == "tag_name":
                return _txt(cc, src).lower()
        return None

    def tag_of(el):
        for c in el.children:
            if c.type in ("start_tag", "self_closing_tag"):
                for cc in c.children:
                    if cc.type == "tag_name":
                        return _txt(cc, src).lower()
        return None

    def attrs_of(el):
        res = {}
        for c in el.children:
            if c.type in ("start_tag", "self_closing_tag"):
                for a in c.children:
                    if a.type == "attribute":
                        name = val = ""
                        for ac in a.children:
                            if ac.type == "attribute_name":
                                name = _txt(ac, src)
                            elif ac.type == "attribute_value":
                                val = _txt(ac, src)
                            elif ac.type == "quoted_attribute_value":
                                # value may be nested in an attribute_value child;
                                # fall back to stripping the quotes.
                                inner = next((x for x in ac.children
                                              if x.type == "attribute_value"), None)
                                val = _txt(inner, src) if inner else \
                                    _txt(ac, src).strip("\"'")
                        # attribute values can contain entities too (&amp; in URLs)
                        res[name.lower()] = html.unescape(val)
        return res

    def inline_children(el):
        out = []
        prev_byte = None
        for i, c in enumerate(el.children):
            # tree-sitter HTML strips whitespace from text nodes around tags;
            # recover any whitespace gap between the previous child and this one.
            if prev_byte is not None and c.start_byte > prev_byte:
                gap = _txt2(prev_byte, c.start_byte, src)
                if gap:
                    out.append({"type": "text", "text": html.unescape(gap)})
            if c.type == "text":
                out.append({"type": "text",
                            "text": html.unescape(_txt(c, src))})
            elif c.type == "entity":
                text = html.unescape(_txt(c, src))
                out.append({"type": "text",
                            "text": text})
            elif c.type == "element":
                # dump_tree(c, src)  # debug
                # treesitter bug, element: text, <br>, text, text, text, <br>
                if str(c).startswith("(element (start_tag (tag_name)") and str(c).endswith("(end_tag (tag_name)))"):
                    out.extend(inline_node(c))
                else:
                    out.extend(inline_children(c))
            elif c.type in ("comment", "doctype"):
                pass  # skip, but still update prev_byte below
            elif c.type in ("start_tag", "self_closing_tag") and direct_tag_of(c) in {"br"}:
                out.append({"type": "hardbreak"})
            # else: silently drop, but still update prev_byte
            prev_byte = c.end_byte
        out = merge_text(out)
        for attr, attrv in attrs_of(el).items():
            if attr == "href":
                assert len(out) == 1
                return [{"type": "link", "url": attrv, "text": out[-1]["text"]}]
        # slack bug, would make deactivate img as "!" + link
        if len(out) == 2 and out[1]["type"] == "link" and out[0]["text"] == "!":
            out[1]["type"] = "image"
            return [out[1]]
        # dump_tree(el, src)  # debug
        return out

    def inline_node(el):
        tag = tag_of(el)
        m = {"strong": "strong", "b": "strong", "em": "emphasis",
             "i": "italic", "del": "strikethrough", "s": "strikethrough"}

        # slack bug: `*code*` would be like <code><i>code</i></code>;
        # `**code**`: <b><code>code</code></b>
        # `***code***`: <b><code><i>code</i></code></b>
        # special cases, hard coding
        if tag == "b" and len(el.children) == 3 and tag_of(el.children[1]) == "code" and len(el.children[1].children) == 3 and tag_of(el.children[1].children[1]) == "i":
            return [{"type": "code_span", "text": "***" + text_only(el.children[1]) + "***"}]
        if tag == "b" and len(el.children) == 3 and tag_of(el.children[1]) == "code":
            return [{"type": "code_span", "text": "**" + text_only(el.children[1]) + "**"}]

        if tag in m:
            return [{"type": m[tag], "children": inline_children(el)}]
        if tag == "code":
            # slack bug: <i> <b> <strong> sometimes would be integrated into code
            children = inline_children(el)
            text = _md_inline(children)
            return [{"type": "code_span", "text": text}]
        if tag == "a":
            at = attrs_of(el)
            return [{"type": "link", "url": at.get("href", ""),
                     "text": text_only(el)}]
        if tag == "img":
            at = attrs_of(el)
            return [{"type": "image", "url": at.get("src", ""),
                     "text": text_only(el)}]
        if tag == "br":
            return [{"type": "hardbreak"}]
        return inline_children(el)

    def text_only(el):
        parts = []
        for i, c in enumerate(el.children):
            if c.type == "text":
                parts.append(html.unescape(_txt(c, src)))
            elif c.type == "entity":
                parts.append(html.unescape(_txt(c, src)))
                # if i + 1 < len(el.children) and el.children[i + 1].type == "text":
                #     parts.append(" ")
            elif c.type == "element":
                parts.append(text_only(c))
            elif c.type in ("start_tag", "self_closing_tag") and direct_tag_of(c) in {"br"}:  # should only have hardbreak in html
                parts.append("\n")
        return "".join(parts)

    def block_node(el):
        tag = tag_of(el)
        if tag in _TAG_LEVEL:
            heading = {"type": "heading", "level": _TAG_LEVEL[tag],
                    "children": inline_children(el)}
            if text_only4node(heading) == "":
                return None
            return heading
        if tag == "p":
            # compute raw inner text (between > and </) — tree-sitter strips
            # leading whitespace from text nodes, but I need it for code blocks
            try:
                inner_start = next(c.end_byte for c in el.children
                                   if c.type == "start_tag")
                inner_end = next(c.start_byte for c in el.children
                                 if c.type == "end_tag")
                raw_text = _txt2(inner_start, inner_end, src)
            except StopIteration:
                raw_text = _txt(el, src)
            # slack bug
            if "prettyprint line" in attrs_of(el).get("class", ""):
                text = text_only(el)
                if text.strip().startswith("```  \n") and text.endswith("\n```"):
                    text = text.strip()[len("```  \n"): -len("\n```")]
                return {"type": "code_block", "attrs": attrs_of(el), "text": text}
            return {"type": "paragraph", "attrs": attrs_of(el),
                    "children": inline_children(el), "_raw": raw_text}
        if tag == "blockquote":
            return {"type": "blockquote", "attrs": attrs_of(el), "children": blocks_in(el)}
        if tag in ("ul", "ol"):
            li_children = []
            for c in el.children:
                if c.type == "element" and tag_of(c) in {"li", "ul", "ol"}:
                    if tag_of(c) == "li":
                        li_children.append(li_node(c))
                    else:
                        li_children.append(
                            {'type': 'list_item', 'is_checked': None, 'children': [block_node(c)]})

            is_todo_list = [c for c in li_children if c["is_checked"] is not None]
            if is_todo_list:
                for c in li_children:
                    if c["children"][0]["type"] != "list" and c["is_checked"] is None:
                        c["is_checked"] = "unchecked"
            return {"type": "list", "ordered": tag == "ol", "start": 1,
                    "children": li_children}
        if tag == "pre":
            code_el = next((c for c in el.children
                            if c.type == "element" and tag_of(c) == "code"), None)
            target = code_el or el
            lang = ""
            if code_el:
                cls = attrs_of(code_el).get("class", "")
                if "language-" in cls:
                    lang = cls.split("language-", 1)[1].split()[0]
            return {"type": "code_block", "attrs": attrs_of(el), "lang": lang, "text": text_only(target)}
        if tag == "hr":
            return {"type": "thematic_break"}
        if tag == "table":
            return html_table(el)
        # wrappers (div, body, html, section, article...) -> descend
        kids = blocks_in(el)
        if len(kids) == 1:
            return kids[0]
        return {"type": "document", "children": kids} if kids else None

    def li_node(el):
        is_checked = None
        # GFM task list in HTML: <li><input type=checkbox [checked]> text</li>
        for c in el.children:
            if c.type == "element" and tag_of(c) == "input":
                a = attrs_of(c)
                if a.get("type", "").lower() == "checkbox":
                    is_checked = "checked" if "checked" in a else "unchecked"
        kids = blocks_in(el)
        if not kids:
            kids = inline_children(el)
            if kids and kids[-1]["type"] == "hardbreak":
                kids = kids[:-1]
            kids = [{"type": "paragraph", "children": kids}]
        else:
            # blocks_in() only captures element children (ul, ol, pre, ...),
            # so text/inline content directly in the <li> is lost when both
            # exist (e.g. <li>text<ul><li>nested</li></ul></li>).
            inline_parts = []
            for c in el.children:
                if c.type == "text":
                    text = html.unescape(_txt(c, src))
                    if text:
                        inline_parts.append({"type": "text", "text": text})
                elif c.type == "entity":
                    text = html.unescape(_txt(c, src))
                    if text:
                        inline_parts.append({"type": "text", "text": text})
                elif c.type == "element":
                    tag = tag_of(c)
                    if tag == "input":
                        ic = inline_children(c)
                        if ic and ic[0]["type"] == "text":
                            ic[0]["text"] = ic[0]["text"].lstrip(" ")
                        inline_parts.extend(ic)
                        continue
                    if tag in _TAG_LEVEL or tag in {"ul", "ol", "pre", "table", "blockquote", "hr"}:
                        continue
                    inline_parts.extend(inline_node(c))
            if inline_parts:
                inline_parts = merge_text(inline_parts)
                kids.insert(0, {"type": "paragraph", "children": inline_parts})
        if kids and kids[-1]["type"] == "hardbreak":
            kids = kids[:-1]
        # slack bug
        if "checked" in attrs_of(el).get("class", ""):
            is_checked = "checked"
        # if "level" in str(kids): dump_tree(el, src)  # debug
        return {"type": "list_item", "is_checked": is_checked, "children": kids}

    def html_table(el):
        rows = []
        align = []

        def walk_rows(container):
            for c in container.children:
                if c.type != "element":
                    continue
                tg = tag_of(c)
                if tg in ("thead", "tbody"):
                    walk_rows(c)
                elif tg == "tr":
                    header = any(tag_of(x) == "th" for x in c.children
                                 if x.type == "element")
                    cells = []
                    for x in c.children:
                        if x.type == "element" and tag_of(x) in ("td", "th"):
                            cells.append({"type": "table_cell",
                                          "children": inline_children(x)})
                    rows.append({"type": "table_row", "header": header,
                                 "children": cells})
        walk_rows(el)
        if rows:
            align = [None] * len(rows[0]["children"])
        return {"type": "table", "align": align, "children": rows}

    def blocks_in(el):
        out = []
        for c in el.children:
            if c.type == "element":
                bn = block_node(c)
                if bn:
                    _html_special_blocks(bn)
                    out.append(bn)
        return out

    def is_line_paragraph_direct_from_html(anode):
        return anode["type"] == "paragraph" and "class" in anode.get("attrs", dict()) \
                        and "line" in anode["attrs"]["class"]

    def _html_special_blocks(node):
        if "children" not in node or not node["children"]:
            return
        
        
        new_children = []
        i = 0
        while i < len(node["children"]):
            child = node["children"][i]
            # Convert $$...$$ blocks into latex_block nodes.
            if child is None:
                i += 1
                continue
            # recursively process nested containers
            if child["type"] in ("blockquote", "list", "list_item", "section", "document"):
                _html_special_blocks(child)

            # ---- case A: separate-paragraph delimiters ----
            # A) $$ / ... / $$ as separate paragraphs (blank-line separated).
            if child["type"] == "paragraph" and text_only4node(child).strip() == "$$":
                closing = None
                for j in range(i + 1, len(node["children"])):
                    if node["children"][j]["type"] == "paragraph" and text_only4node(node["children"][j]).strip() == "$$":
                        closing = j
                        break
                if closing is not None and closing > i + 1:
                    parts = []
                    for k in range(i + 1, closing):
                        p = node["children"][k]
                        if p["type"] == "paragraph":
                            text = text_only4node(p)
                            lines = text.split("\n")
                            parts.append("\n".join(lines))
                    content = "\n".join(parts).strip()
                    new_children.append({"type": "latex_block", "text": content})
                    i = closing + 1
                    continue

            # ---- case B: self-contained $$...$$ inside one paragraph ----
            # B) $$\\n...\\n$$ inside a single paragraph (no blank lines).
            if child["type"] == "paragraph":
                full = text_only4node(child).strip()
                if full.startswith("$$") and full.endswith("$$") and len(full) > 4:
                    inner = full[2:-2].strip()
                    if inner:
                        new_children.append({"type": "latex_block", "text": inner})
                        i += 1
                        continue
            
            # convert thematic_break ... thematic_break into possible yaml comment block
            if child["type"] == "thematic_break":
                closing = None
                for j in range(i + 1, len(node["children"])):
                    p = node["children"][j]
                    if p["type"] == "thematic_break":
                        closing = j
                        break
                    elif is_line_paragraph_direct_from_html(p) \
                        and re.match(r'^(?P<indent>[ \t]*)(?P<key>[\w\-\.]+)\s*:\s*(?P<value>.*)$', text_only4node(p), re.IGNORECASE):
                        pass
                    else:
                        break
                if closing is not None and closing > i + 1:
                    parts = []
                    for k in range(i + 1, closing):
                        p = node["children"][k]
                        if p["type"] == "paragraph":
                            text = text_only4node(p)
                            lines = text.split("\n")
                            parts.append("\n".join(lines))
                    content = "\n".join(parts).strip()
                    new_children.append({"type": "metadata", "format": "yaml", "text": content})
                    i = closing + 1
                    continue

            # slack bug: Delete softbreaks automatically added while convert markdown to html
            # Delete soft breaks added between code lines
            # and convert those lines into code_span
            if child["type"] == "paragraph":
                def _raw_or_para(p):
                    return p.get("_raw", text_only4node(p))
                text = _raw_or_para(child).strip()
                m = re.match(r'^```(\w+)$', text)
                if m:
                    lang = m.group(1)
                    closing = None
                    for j in range(i + 1, len(node["children"])):
                        p = node["children"][j]
                        if p["type"] == "paragraph" and _raw_or_para(p).strip() == "```":
                            closing = j
                            break
                    if closing is not None and closing > i + 1:
                        code_lines = []
                        valid = True
                        for k in range(i + 1, closing):
                            p = node["children"][k]
                            if p["type"] != "paragraph":
                                valid = False
                                break
                            if "line" not in p.get("attrs", {}).get("class"):
                                valid = False
                                break
                            pt = _raw_or_para(p)
                            code_lines.append(pt)
                        if valid:
                            content = "\n".join(code_lines)
                            new_children.append({
                                "type": "code_block",
                                "lang": lang,
                                "text": content
                            })
                            i = closing + 1
                            continue

            # Delete soft breaks added between table lines
            # and Convert "|H1|H2|H3...|\n|---|---|---|\n|c1|c2|c3...|\n" into table
            # here slack conversion: table like `| :--- | :----: | ----: |` would be transfered into `|---|----|---|`
            def seems_to_be_a_table_line(line, cnt=-1):
                return len(line) > 3 and line[0] == '|' and line[-1] == '|' \
                    and (cnt == - 1 or line.count("|") - line.count("\|")== cnt + 1) \
                    and '||' not in line

            if is_line_paragraph_direct_from_html(child):
                text = text_only4node(child)
                if seems_to_be_a_table_line(text):
                    cells = text[1:-1].split("|")
                    cell_num = len(cells)
                    print("catch it!", cells, cell_num, new_children[-2:])
                    print("Test", text_only4node(new_children[-1]))
                    print(len([c for c in cells if len(c.strip()) > 0 and c.strip() == "-" * len(c.strip()) ]) == cell_num, len(new_children) >= 2, len(text_only4node(new_children[-1])) == 0, seems_to_be_a_table_line(text_only4node(new_children[-2]), cell_num))
                    if len([c for c in cells if len(c.strip()) > 0 and c.strip() == "-" * len(c.strip()) ]) == cell_num \
                        and len(new_children) >= 1 \
                        and seems_to_be_a_table_line(text_only4node(new_children[-1]), cell_num):
                        print("catch it!2", cells, cell_num, new_children[-1])
                        closing = None
                        for j in range(i + 1, len(node["children"])):
                            p = node["children"][j]
                            print("later", text_only4node(p))
                            if is_line_paragraph_direct_from_html(p) and seems_to_be_a_table_line(text_only4node(p), cell_num):
                                print("pass")
                                closing = j
                            else:
                                break
                        if closing is not None and closing > i + 1:
                            parts = [text_only4node(new_children[-1])]
                            for k in range(i, closing + 1):
                                p = node["children"][k]
                                if p["type"] == "paragraph":
                                    text = text_only4node(p)
                                    lines = text.split("\n")
                                    parts.append("\n".join(lines))
                            content = "\n".join(parts).strip()
                            print("content", content)
                            new_children = new_children[:-1]
                            new_children.append(parse_markdown(content)["children"][0])
                            i = closing + 1
                            continue

            # slack bug: Delete reduplicated table cells items following table
            # e.g.:
            # Original Table:
            # > | k | v |
            # > | --- | --- |
            # > | a | 1 |
            # After Conversion:
            # > | k | v |
            # > | --- | --- |
            # > | a | 1 |
            # > k
            # > v
            # > a
            # > 1


            # final, not a part of previous logic
            new_children.append(child)
            i += 1
        node["children"] = new_children

    def reorg_html(tree, start_ind=0):
        if "children" not in tree or len(tree["children"]) <= 1:
            return tree
        children = tree["children"][:start_ind]
        while start_ind < len(tree["children"]):
            c = tree["children"][start_ind]
            if c["type"] == "heading":
                j = start_ind + 1
                while j < len(tree["children"]):
                    if tree["children"][j]["type"] == "heading" and tree["children"][j]["level"] <= c["level"]:
                        break
                    j += 1
                subchildren = tree["children"][start_ind:j]
                start_ind = j
                new_node = {"type": "document", "children": subchildren}
                children.append(reorg_html(new_node, start_ind=1))
            else:
                children.append(reorg_html(c))
                start_ind += 1
        tree["children"] = children
        return tree


    root = tree.root_node
    children = []
    for c in root.children:
        if c.type == "element":
            bn = block_node(c)
            if bn:
                children.append(bn)
        elif c.type == "comment":
            m = re.match(r'<!--\s*(yaml|toml)\s+metadata:\n([\s\S]*)\n\s*-->$', _txt(c, src), re.IGNORECASE)
            if m:
                children.append({"type": "metadata", "format": m.group(1).lower(), "text": m.group(2).rstrip()})
    ntree = {"type": "document", "children": children}
    _html_special_blocks(ntree)
    ntree = reorg_html(ntree)
    return ntree


# ===========================================================================
# middle -> MARKDOWN
# ===========================================================================

def _md_blocks(nodes, parent_type, depth):
    parts = []
    for node in nodes:
        text = _md_block(node, parent_type, depth)
        if text is None:
            continue
        if parent_type in {"paragraph", "document"} and node["type"] in {"paragraph"} \
                or parent_type not in {"list"} and node["type"] in {"list"}:
            if len(text) == 0 and len(parts) > 0:
                continue
            if not text.endswith("\n") and not text.endswith("  ") and not text.endswith("\\"):
                text += "\n"
        if node["type"] == "document":
            snode = node["children"][0]
        else:
            snode = node
        if snode["type"] == "heading" and (len(parts) > 0 and not parts[-1].endswith("\n") and not len(parts[-1]) == 0):
            text = "\n" + text
        parts.append(text)

    if parent_type == "code_block":
        return "\n".join(parts)
    else:
        return "\n".join(p for p in parts if len(p) > 0)


def _md_block(n, parent_type, depth):
    t = n["type"]
    if t == "document":
        return _md_blocks(n["children"], t, depth)
    if t == "metadata":
        fence = "---" if n.get("format") == "yaml" else "+++"
        return f"{fence}\n{n['text']}\n{fence}"
    if t == "heading":
        return "#" * n["level"] + " " + _md_inline(n["children"])
    if t == "paragraph":
        return _md_inline(n["children"])
    if t == "thematic_break":
        return "---"
    if t == "code_block":
        return f"```{n.get('lang','')}\n{n['text']}\n```"
    if t == "latex_block":
        return f"$$\n{n['text']}\n$$"
    if t == "blockquote":
        inner_lines = _md_blocks(n["children"], t, 0).split("\n")
        parts = []
        for ln in inner_lines:
            if ln and ln != ">" and not (ln.startswith(">") and ln.lstrip(">")[0] == " "):
                parts.append("> " + ln)
            else:
                parts.append(">" + ln)
        return "\n".join(parts)
    if t == "list":
        return _md_list(n, depth)
    if t == "table":
        return _md_table(n)
    return _md_inline(n.get("children", [])) if "children" in n else n.get("text", "")


def _md_list(n, depth):
    items = []
    ordered = n.get("ordered", False)
    num = n.get("start", 1)
    for item in n["children"]:
        assert item["type"] == "list_item"
        if len(item["children"]) == 1 and item["children"][0]["type"] == "list":
            items.append(_md_blocks(
                item["children"], item["type"], depth + 1).rstrip())
        else:
            marker = (f"{num}. " if ordered else "- ")
            if item.get("is_checked") == "checked":
                marker += "[x] "
            elif item.get("is_checked") == "unchecked":
                marker += "[ ] "
            body = _md_blocks(item["children"], item["type"], depth + 1)
            item_lines = body.split("\n")
            first_text = marker + _md_blocks(item["children"][:1], item["type"], depth + 1)
            print("is first text too large?", first_text, "\nitem", item)
            first_line = marker + item_lines[0]
            rest = [("    " + ln if ln else "") for ln in item_lines[first_line.count("\n") + 1:]]
            print("rest", rest, n)
            items.append("\n".join([first_line] + rest).strip())
        num += 1
    block = "\n".join(items)
    return block


def _md_table(n):
    rows = n["children"]
    if not rows:
        return ""
    align = n.get("align") or [None] * len(rows[0]["children"])

    def render_row(cells):
        return "| " + " | ".join(_md_inline(c["children"]) for c in cells) + " |"

    def delim(header):
        return "-" * len(header) if len(header) > 0 else "--"

    header = rows[0]
    out = [render_row(header["children"])]
    headers = out[0][1:-1].split("|")
    out.append("|" + "|".join(delim(header) for header in headers) + "|")
    for r in rows[1:]:
        out.append(render_row(r["children"]))
    return "\n".join(out)


def _md_inline(nodes):
    out = []
    for n in nodes:
        t = n["type"]
        if t == "text":
            out.append(n["text"])
        elif t == "emphasis":
            out.append("*" + _md_inline(n["children"]) + "*")
        elif t == "strong":
            out.append("**" + _md_inline(n["children"]) + "**")
        elif t == "italic":
            out.append("*" + _md_inline(n["children"]) + "*")
        elif t == "strikethrough":
            out.append("~~" + _md_inline(n["children"]) + "~~")
        elif t == "code_span":
            out.append("`" + n["text"] + "`")
        elif t == "link":
            text = n.get("text", "")
            url = n.get("url", "")
            if text == url or not text:
                out.append(url)
            else:
                out.append(f"[{text}]({url})")
        elif t == "image":
            text = n.get("text", "")
            out.append(f"![{text}]({n['url']})")
        elif t == "wikilink":
            url = n.get("url", "")
            text = n.get("text", "")
            if text:
                out.append(f"[[{url}|{text}]]")
            else:
                out.append(f"[[{url}]]")
        elif t == "embed":
            url = n.get("url", "")
            text = n.get("text", "")
            if text:
                out.append(f"![[{url}|{text}]]")
            else:
                out.append(f"![[{url}]]")
        elif t == "hardbreak":
            out.append("  \n")
        # elif t == "softbreak":
        #     out.append("\n")
        else:
            out.append(n.get("text", ""))
    return "".join(out)


def dump_markdown(node):
    return _md_blocks(node.get("children", []), node["type"], 0).rstrip("\n") + "\n"


# ===========================================================================
# middle -> HTML
# ===========================================================================


def _html_block(n):
    t = n["type"]
    if t == "document":
        return "\n".join(_html_block(c) for c in n["children"])
    if t == "metadata":
        return f"<!-- {n.get('format','yaml')} metadata:\n{n['text']}\n-->"
    if t == "heading":
        return f"<h{n['level']}>{_html_inline(n['children'])}</h{n['level']}>"
    if t == "paragraph":
        return f"<p>{_html_inline(n['children'])}</p>"
    if t == "thematic_break":
        return "<hr>"
    if t == "code_block":
        cls = f' class="language-{n["lang"]}"' if n.get("lang") else ""
        return f"<pre><code{cls}>{_esc(n['text'])}</code></pre>"
    if t == "latex_block":
        return f"<pre><code class=\"language-latex\">{_esc(n['text'])}</code></pre>"
    if t == "blockquote":
        inner = "\n".join(_html_block(c) for c in n["children"])
        return f"<blockquote>\n{inner}\n</blockquote>"
    if t == "list":
        tag = "ol" if n.get("ordered") else "ul"
        items = "\n".join(_html_li(it) for it in n["children"])
        return f"<{tag}>\n{items}\n</{tag}>"
    if t == "table":
        return _html_table(n)
    return _html_inline(n.get("children", []))


def _html_li(it):
    body = "".join(_html_block_inlineable(c) for c in it["children"])
    if it.get("is_checked") == "checked":
        body = '<input type="checkbox" checked> ' + body
    elif it.get("is_checked") == "unchecked":
        body = '<input type="checkbox"> ' + body
    return f"<li>{body}</li>"


def _html_block_inlineable(c):
    # a single paragraph inside <li> renders inline (no <p>) for compactness
    if c["type"] == "paragraph":
        return _html_inline(c["children"])
    return _html_block(c)


def _html_table(n):
    rows = n["children"]
    if not rows:
        return "<table></table>"
    out = ["<table>"]
    for r in rows:
        cell_tag = "th" if r.get("header") else "td"
        cells = "".join(f"<{cell_tag}>{_html_inline(c['children'])}</{cell_tag}>"
                        for c in r["children"])
        out.append(f"<tr>{cells}</tr>")
    out.append("</table>")
    return "\n".join(out)


def _html_inline(nodes):
    out = []
    for n in nodes:
        t = n["type"]
        if t == "text":
            out.append(_esc(n["text"]))
        elif t == "strong":
            out.append("<strong>" + _html_inline(n["children"]) + "</strong>")
        elif t == "italic":
            out.append("<i>" + _html_inline(n["children"]) + "</i>")
        elif t == "emphasis":
            out.append("<em>" + _html_inline(n["children"]) + "</em>")
        elif t == "strikethrough":
            out.append("<del>" + _html_inline(n["children"]) + "</del>")
        elif t == "code_span":
            out.append("<code>" + _esc(n["text"]) + "</code>")
        elif t == "link":
            url = _esc(n.get("url", ""))
            title = _esc(n.get("title", ""))
            text =  _esc(n.get("text", ""))
            if title:
                out.append(f'<a href="{url}" title="{title}">{text}</a>')
            else:
                out.append(f'<a href="{url}">{text}</a>')
        elif t == "image":
            text = _esc(n["text"])
            out.append(f'<img src="{_esc(n["url"])}"> {text} </img>')
        elif t == "wikilink":
            url = n.get("url", "")
            text = n.get("text", "")
            if text:
                out.append(f"[[{url}|{text}]]")
            else:
                out.append(f"[[{url}]]")
        elif t == "embed":
            url = n.get("url", "")
            text = n.get("text", "")
            if text:
                out.append(f"![[{url}|{text}]]")
            else:
                out.append(f"![[{url}]]")
        elif t == "hardbreak":
            out.append("<br>\n")
        # elif t == "softbreak":
        #     out.append("\n")
        else:
            out.append(_esc(n.get("text", "")))
    return "".join(out)


# ===========================================================================
# latex block post-processing: merge $$...$$ paragraph sequences
# ===========================================================================
def dump_html(node):
    return "\n".join(_html_block(c) for c in node.get("children", [])).rstrip("\n") + "\n"


# ===========================================================================
# convenience + diagnostics
# ===========================================================================
def markdown_to_html(text):
    tree = parse_markdown(text)
    print(json.dumps(tree, indent=4))
    return dump_html(tree)


def html_to_markdown(text):
    tree = parse_html(text)
    print(json.dumps(tree, indent=4))
    return dump_markdown(tree)


def diagnose(md_or_html, kind="markdown"):
    """Print the raw tree-sitter tree so you can verify node names locally."""
    if kind == "markdown":
        _, block_lang, _ = _languages()
        parser = _make_parser(block_lang)
    else:
        html_lang, _, _ = _languages()
        parser = _make_parser(html_lang)
    tree = parser.parse(md_or_html.encode("utf-8"))
    print(tree.root_node)


if __name__ == '__main__':
    # with open("obsidian_canvas_fixture.md", "r", encoding="utf-8") as fin:
    #     out = markdown_to_html(fin.read())
    # with open("obsidian_canvas_fixture.md.html", "w", encoding="utf-8") as fout:
    #     fout.write(out)
    # with open("obsidian_canvas_fixture.md.html", "r", encoding="utf-8") as fin:
    #     out = html_to_markdown(fin.read())
    # with open("obsidian_canvas_fixture.md.html.md", "w", encoding="utf-8") as fout:
    #     fout.write(out)
    with open("F0BBVUXMRG9_Obsidian_____Canvas_Round-Trip_Fixture.html", "r", encoding="utf-8") as fin:
        out = html_to_markdown(fin.read())
    with open("F0BBVUXMRG9_Obsidian_____Canvas_Round-Trip_Fixture.html.md", "w", encoding="utf-8") as fout:
        fout.write(out)
